TA Tool: Check for different or missing join secrets
weka/tools pull request #355
Opened 2024-09-11 14:01 UTC by djgalloway

2024-09-12 03:09 UTC, vince-weka approved these changes

2024-09-12 03:09 UTC, vince-weka requested changes
Wrong repo...

2024-09-12 03:09 UTC, closed without merging

2024-09-12 03:10 UTC, vince-weka commented
Please resubmit in the wekachecker repo.Vince FlemingProduct ***@***.*** ­W www.weka.io ­  ­On Sep 11, 2024, at 7:02 AM, David Galloway ***@***.***> wrote:﻿



You can view, comment on, or merge this pull request online at:
  https://github.com/weka/tools/pull/355

Commit Summary

  f939a77  TA Tool: Check for different or missing join secrets


File Changes  (1 file)

  
    A
    install/scripts.d/ta/710_missing_join_secrets.sh
    (65)
  


Patch Links:

  https://github.com/weka/tools/pull/355.patch
  https://github.com/weka/tools/pull/355.diff


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2024-09-20 13:48 UTC, shazad-weka commented on install/scripts.d/ta/710_missing_join_secrets.sh
This does not check join_secret for any of the protocol containers does that matter?

2024-09-20 14:00 UTC, shazad-weka commented on install/scripts.d/ta/710_missing_join_secrets.sh
should you also check --stable resources?

2024-09-27 15:46 UTC, djgalloway commented on install/scripts.d/ta/710_missing_join_secrets.sh
It can't hurt I think?  We'd want to check all staged and stable resources.  A secret should either be present in all or missing from all.

2024-09-27 15:50 UTC, djgalloway commented
> Wrong repo...

I am all for having our tools split out into separate repos.  But why is wekachecker in _this_ repo at all if it's being maintained elsewhere?